# https://prettier.io/docs/en/options.html
arrowParens: avoid
bracketSameLine: false
bracketSpacing: true
endOfLine: lf
jsxSingleQuote: false
printWidth: 100
proseWrap: always
quoteProps: as-needed
semi: true
singleQuote: true
tabWidth: 4
trailingComma: all
useTabs: false
