printWidth: 100
tabWidth: 4
useTabs: false
semi: true
singleQuote: true
quoteProps: consistent
jsxSingleQuote: false
trailingComma: all
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: avoid
proseWrap: always
endOfLine: lf
